version: "3.8"

services:
  frontend:
    build: ./FrontendTemplate
    container_name: chor_ui
    ports:
      - '8080:8080'
    stdin_open: true
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build: 
      context: ./BakcendTemplate
    container_name: node_api
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - my_network
networks:
  my_network:
    

  # database:
  #   image: mongo
  #   container_name: mongo_db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - /home/noneed/mongo-backup:/data/db
  #   networks:
  #     - mern-network


